export type ErrorCode =
  | AccountErrorCodeEnum
  | CommonErrorCodeEnum
  | TrainingLogErrorCodeEnum;

export enum AccountErrorCodeEnum {
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS',
  CODE_ALREADY_CONFIRMED = 'CODE_ALREADY_CONFIRMED',
  CODE_INCORRECT = ' CODE_INCORRECT',
  CODE_EXPIRED = 'CODE_EXPIRED',
  CODE_INVALID = 'CODE_INVALID',
  EMAIL_ALREADY_CONFIRMED = 'EMAIL_ALREADY_CONFIRMED',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NO_RESPONSE_FROM_OAUTH = 'NO_RESPONSE_FROM_OAUTH',
  UNSUPPORTED__OAUTH_PROVIDER = 'UNSUPPORTED__OAUTH_PROVIDER',
  EMAIL_OR_PASSWORD_INCORRECT = 'EMAIL_OR_PASSWORD_INCORRECT',
  NOT_OWNER = 'NOT_OWNER',
}

export enum CommonErrorCodeEnum {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}

export enum TrainingLogErrorCodeEnum {
  TRAINING_LOG_ALREADY_EXISTS = 'TRAINING_LOG_ALREADY_EXISTS',
  TRAINING_LOG_NOT_FOUND = 'TRAINING_LOG_NOT_FOUND',
}
