export type ErrorCode =
  | AccountErrorCodeEnum
  | CommonErrorCodeEnum
  | TrainingJournalErrorCodeEnum
  | SessionErrorCodeEnum
  | AuthErrorCodeEnum;

export enum AccountErrorCodeEnum {
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS',
  CODE_ALREADY_CONFIRMED = 'CODE_ALREADY_CONFIRMED',
  CODE_INCORRECT = ' CODE_INCORRECT',
  CODE_EXPIRED = 'CODE_EXPIRED',
  CODE_INVALID = 'CODE_INVALID',
  EMAIL_ALREADY_CONFIRMED = 'EMAIL_ALREADY_CONFIRMED',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
}

export enum AuthErrorCodeEnum {
  NOT_OWNER = 'NOT_OWNER',
  UNAUTHORIZED = 'UNAUTHORIZED',
  EMAIL_OR_PASSWORD_INCORRECT = 'EMAIL_OR_PASSWORD_INCORRECT',
  NO_RESPONSE_FROM_OAUTH = 'NO_RESPONSE_FROM_OAUTH',
  UNSUPPORTED_OAUTH_PROVIDER = 'UNSUPPORTED__OAUTH_PROVIDER',
}

export enum SessionErrorCodeEnum {
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
}

export enum CommonErrorCodeEnum {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
}

export enum TrainingJournalErrorCodeEnum {
  TRAINING_JOURNAL_ALREADY_EXISTS = 'TRAINING_JOURNAL_ALREADY_EXISTS',
  TRAINING_JOURNAL_NOT_FOUND = 'TRAINING_JOURNAL_NOT_FOUND',
}
