export enum AccountErrorCodeEnum {
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS',
  CODE_ALREADY_CONFIRMED = 'CODE_ALREADY_CONFIRMED',
  CODE_INCORRECT = ' CODE_INCORRECT',
  CODE_EXPIRED = 'CODE_EXPIRED',
  CODE_INVALID = 'CODE_INVALID',
  EMAIL_ALREADY_CONFIRMED = 'EMAIL_ALREADY_CONFIRMED',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
  EMAIL_NOT_CONFIRMED = 'EMAIL_NOT_CONFIRMED',
  UNAUTHORIZED = 'UNAUTHORIZED',
  NO_RESPONSE_FROM_OAUTH = 'NO_RESPONSE_FROM_OAUTH',
  UNSUPPORTED__OAUTH_PROVIDER = 'UNSUPPORTED__OAUTH_PROVIDER',
}
